# .devcontainer/docker-compose.yml
services:
  apache_spark:
    # Mant√©m o mesmo tag se quiseres continuar a chamar "pmglok/spark:active"
    image: pmglok/spark:active
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        GIT_COMMIT: ${GIT_COMMIT:-}
        BUILD_DATE: ${BUILD_DATE:-}
    user: vscode
    volumes:
      - ..:/workspaces/ApacheSpark-CD:cached
      - sparkdata:/workspaces/ApacheSpark-CD/data
    command: sleep infinity
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres_db
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    mem_limit: 1g
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  pgdata:
  sparkdata:
