name: Build & Push to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"     # ex: v2.1.
  workflow_dispatch:
    inputs:
      version:
        description: "Versão para promover (ex: 0.1.5) — vai criar/atualizar :active"
        required: true
        type: string


env:
  IMAGE_NAME: pmglok/spark

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: tags
        shell: bash
        run: |
          set -euo pipefail
          BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          echo "build_date=${BUILD_DATE}" >> $GITHUB_OUTPUT

          # Caso 1: manual run -> promover versão existente para :active
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ inputs.version }}"
            echo "mode=promote" >> $GITHUB_OUTPUT
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Caso 2: tag push -> build+push versão e :active
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "mode=release" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT


      - name: Build and push (release)
        if: steps.tags.outputs.mode == 'release'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          tags: pmglok/spark:${{ steps.tags.outputs.version }},pmglok/spark:active
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            BUILD_DATE=${{ steps.tags.outputs.build_date }}
      
      - name: Promote existing version to :active (manual)
        if: steps.tags.outputs.mode == 'promote'
        shell: bash
        run: |
          set -euo pipefail
          VERSION="${{ steps.tags.outputs.version }}"
          docker pull pmglok/spark:${VERSION}
          docker tag pmglok/spark:${VERSION} pmglok/spark:active
          docker push pmglok/spark:active


